Update git submodules
* Update src/sonic-utilities from branch 'broadcom_sonic'
  to 62ff83583d7a8b5cf4236ad96ce8c02bc5101550
  - Merge "[JIRA SONIC-11093] AS9716 command "show interface transceiver eeprom" failing because problems reading transceiver" into broadcom_sonic
  - [JIRA SONIC-11093] AS9716 command "show interface transceiver eeprom" failing because problems reading transceiver
    
    This is to address the following failure:
    
    admin@F1-T1-TH3-9716:~$ sudo sfputil show eeprom -p Ethernet84 --raw
    Traceback (most recent call last):
      File "/usr/bin/sfputil", line 12, in <module>
        sys.exit(cli())
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 410, in eeprom
        if platform_sfputil.is_valid_sfputil_port(logical_port) == 0:
    NameError: global name 'logical_port' is not defined
    
    Signed-off-by: Dante (Kuo-Jung) Su <dante.su@broadcom.com>
    Change-Id: I570c6adf44d2f8ef98c2ffa1ad2c3bc5563d1d2d